services:
  node-install:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: npm install

  node-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8000"

  node-build:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"

  node-preview:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4173:4173"
    command: sh -c "npm install && npm run preview -- --host 0.0.0.0"

  node-test:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - CI=true
    command: sh -c "npm install && npm test"

  playwright:
    image: mcr.microsoft.com/playwright:v1.48.2-focal
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - CI=true
    network_mode: host
    command: sh -c "npm install && ./scripts/e2e-test.sh"